
<navigation>
  <div id="topbar">
    <p>LOGO</p>
    <i id="hamburger" class="fas fa-bars"></i>
  </div>

    <ul>

        <li><a href="index.shtml">Home</a></li>
        <li><a href="aboutUs.shtml">About us</a></li>
        <li><a href="menu.shtml">Menu</a></li>
        <li><a href="contact.shtml">Contact</a></li>
          <li><a href="activities.shtml">Activities</a></li>
    </ul>
</navigation>
